### PR TITLE
Add compatiblity with IdeaVim 2.25.0 and fix deprecations

### LINKED ISSUE #101: Crash with IdeaVim 2.25.0-eap.3
After updating IdeaVim to 2.25.0-eap.3, WhichKey (0.10.3) will crash on any keypress and completely disable functionality, even just normal IdeaVim editing, leading to need for you to disable the plugin. 

This seems to be cause of using a deprecated API (com/maddyhome/idea/vim/command/CommandState.kt), which was recently removed <https://github.com/JetBrains/ideavim/commit/ab635972cc6cab7275658c545674262d35819e27>  

It seems like the alternative is to use `injector.vimState` (according to the deprecated marker)

<details>
<summary>Full stacktrace</summary>

```java
java.lang.NoClassDefFoundError: com/maddyhome/idea/vim/command/CommandState
	at eu.theblob42.idea.whichkey.WhichKeyTypeActionHandler.beforeExecute(WhichKeyTypeActionHandler.kt:39)
	at com.intellij.openapi.editor.actionSystem.TypedAction.beforeActionPerformed(TypedAction.java:191)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedImmediately(EditorImpl.java:1449)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1434)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3837)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1272)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:247)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6628)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2901)
	at java.desktop/java.awt.Component.processEvent(Component.java:6450)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5043)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4871)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:886)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1162)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:849)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent$lambda$1(IdeKeyboardFocusManager.kt:48)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent$lambda$2(IdeKeyboardFocusManager.kt:54)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:958)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:958)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.kt:54)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4920)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4871)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:585)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:518)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$17(IdeEventQueue.kt:474)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction$lambda$6(AnyThreadWriteThreadingSupport.kt:274)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:274)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runPreventiveWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:218)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:474)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10$lambda$9(IdeEventQueue.kt:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:864)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10(IdeEventQueue.kt:306)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:958)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:958)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12(IdeEventQueue.kt:301)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:341)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.maddyhome.idea.vim.command.CommandState PluginClassLoader(plugin=PluginDescriptor(name=Which-Key, id=eu.theblob42.idea.whichkey, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2025.1/IDEA_Which-Key-0.10.3.jar, version=0.10.3, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IdeaVim, id=IdeaVIM, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2025.1/IdeaVIM, version=2.25.0-eap.3, package=null, isBundled=false), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 69 more
```
</details>

### PR DESCRIPTION
**Pull request by davfsa**
Closes #101 

*Note: This was a simple replacement with the new APIs for the most part, but I am a bit skeptical about 'src/main/kotlin/eu/theblob42/idea/whichkey/config/MappingConfig.kt', even tho it all seems to work.*

### CODE REVIEW

**Comment by TheBlob42** [comment]
Please rebase your PR to the latest `main`

**Comment by davfsa** [comment]
@TheBlob42 rebased :)

**Comment by TheBlob42** [comment]
Well you actually **merged** the changes from `main` into your branch 😅 
While this works, I would prefer a [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) to avoid merge commits (personal preference), especially that I would now need to create a second merge commit to merge your changes.

Let me know if you need further advice on this

I will still have a look into the changes and review them :)

**Comment by davfsa** [comment]
Thanks my bad! Sorry for that!

Over time I have just treated rebase as "please bring your branch up to date with master", I was not aware you were doing merge commits (so used to squash, lol). Will get that fixed and sorry again!

**Comment by TheBlob42** [comment]
To make it clear: These are no issues that you have introduced or forgotten, but that come with using the new API and to adapt to the changes introduced there 🙃

**Comment by davfsa** [comment]
> I have even found another issue [here](https://github.com/TheBlob42/idea-which-key/blob/main/src/main/kotlin/eu/theblob42/idea/whichkey/WhichKeyActionListener.kt?rgh-link-date=2025-05-21T15%3A27%3A25Z#L137) that should be tackled by using KeyHandler.getInstance().reset(vimEditor) instead to also reset the CommandBuilder (otherwise pressing <C-w>=w would still trigger <C-w>w since the CommandBuilder was not properly resetted)

Interesting. I cannot seem to reproduce this, it seems to work as expected when I try it.

> I would like to have all related commits in one PR to be able to test the whole solution

I always leave `Allow edits by maintainers` on, so you should be able to push to this pr directly :)

Feel free to edit as you wish! If there is anything I can help with, do let me know!

> To make it clear: These are no issues that you have introduced or forgotten, but that come with using the new API and to adapt to the changes introduced there 🙃

No problem, hahaha. I fully expected something like that to happen, so I have been daily driving this pull request since I opened it to try and spot any unexpected behaviors (which none so far!). I have not tried all possible combinations to try and break it (as I dont think i even know all the powerful things IdeaVim has support for and WhichKey has to work with).

**Comment by TheBlob42** [comment]
Quite a few changes, but that should cover all edge cases I could identify.
Happy if you can test this also from your end

**Comment by davfsa** [comment]
Been running the new version since yesterday afternoon and today morning and it seems to be working fine!

Thanks @TheBlob42 !
